#This is a sample answer yaml file for the KKE Devops task deploy-voting app on k8s 

apiVersion: v1
kind: Service                                                                     
metadata:                                                                         
  creationTimestamp: null                                                         
  labels:                                                                         
    app: db-deployment
  name: db	
  namespace: vote
spec:                                                                             
  ports:                                                                          
  - port: 5432                                                                    
    protocol: TCP                                                                 
    targetPort: 5432   
  selector:                                                                       
    app: db-deployment                                                         
  type: ClusterIP
