#This is a sample answer yaml file for the KKE Devops task deploy-voting app on k8s 

apiVersion: v1
kind: Service                                                                     
metadata:                                                                         
  creationTimestamp: null                                                         
  labels:                                                                         
    app: redis-deployment
  name: redis
  namespace: vote
spec:                                                                             
  ports:                                                                          
  - port: 6379                                                                    
    protocol: TCP                                                                 
    targetPort: 6379 	
  selector:                                                                       
    app: redis-deployment                                                         
  type: ClusterIP
